### PR TITLE
JOSM #21150: Add @BasicWiremock annotation

### PR DESCRIPTION
**Pull request by tsmock**
This also adds an @HTTP annotation.

### CODE REVIEW

**Comment by tsmock** [comment]
I'm reducing the diff right now. It is *only* reordering the imports.

My IDE reordered the static imports after the non-static imports, and I'm going back and fixing that right now.

**Comment by tsmock** [comment]
Run prior to fixing ordering:
https://github.com/openstreetmap/josm/actions/runs/1053830785

The failing test is `Java 8 on windows-latest`, specifically `org.openstreetmap.josm.data.projection.ProjectionRegressionTest`. Everything else is green.

**Comment by tsmock** [comment]
I'm going to do some force-pushes for bisecting the failing test on Windows (I don't have a Windows system).

If GitHub is smart, it will remember that it ran the action already on cac1721, but have a link: https://github.com/openstreetmap/josm/pull/73/checks?check_run_id=3128372623.

Don't bother having the workflow rerun -- the workflow is running on my fork as well.

**Comment by tsmock** [comment]
> I'm going to do some force-pushes for bisecting the failing test on Windows (I don't have a Windows system).
> 
> If GitHub is smart, it will remember that it ran the action already on [cac1721](https://github.com/openstreetmap/josm/commit/cac17211ccc4eb6f4f99009a8d5e33594782e9bb), but have a link: https://github.com/openstreetmap/josm/pull/73/checks?check_run_id=3128372623.
> 
> Don't bother having the workflow rerun -- the workflow is running on my fork as well.

Never mind. It looks like master is failing on Java 8 Windows as well.

**Comment by don-vip** [comment]
Applied in https://josm.openstreetmap.de/changeset/18106/josm/

**Pull request closed without merging**
